# Source: cluster-api-byoh/templates/machinedeployment.yaml
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: 098fa8c9-md-normal
  namespace: 098fa8c9
spec:
  template:
    spec: {}
